### ISSUE TITLE
loadModel crashed with lid.176.ftz

### ISSUE THREAD

**Issue by nemesisqp** [karmdesai/fastTextWeb#1]
model is from `https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz`
node `12 LTS`

**Comment by karmdesai** [comment]
@nemesisqp Can you share your code?

**Comment by nemesisqp** [comment]
Maybe this lib can't load that model, the model worked fine with native fasttext.exe but exec for every request is not optimal, which nodejs version you are using ?
```
const fastText = require('fasttextweb');
fastText.loadModel('./lid.176.ftz');
console.log(fastText.makePrediction('predict-prob', "tiếng việt", '1', '0.0'));
```

error
![image](https://user-images.githubusercontent.com/1621069/71047100-183ca180-216d-11ea-8021-3518ffd65584.png)

**Comment by karmdesai** [comment]
@nemesisqp Sorry, if you want to load a model, you have to put 'working/' before the relative file path. I just updated the documentation to reflect this. Here's the code that I used and it worked!

`const fastText = require('fasttextweb');
fastText.loadModel('working/lid.176.ftz');
console.log(fastText.makePrediction('predict-prob', "tiếng việt", '1', '0.0'));`

The output looks something like this:
`__label__vi 0.995981`

**Comment by nemesisqp** [comment]
with 'working/' model path it worked on my end too, now I can ditch `process.spawn` code 😄, thanks you for this project
